version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build1 started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build1 completed on `date`
      - sam package --template-file s3-upload-lambda-template.yaml --output-template-file s3-upload-lambda-output.yaml --s3-bucket anastasiia-vasylieva-images --s3-prefix s3-upload.zip
artifacts:
  files:
    - s3-upload-lambda-output.yaml