AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaApplication:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.epam.handler::SQSProcessHandler
      FunctionName: sqs-retrieve-lambda
      Runtime: java8
      Description: Lambda that retrieve messages from SQS
      MemorySize: 512
      Timeout: 10
      Policies:
        - AWSLambda_FullAccess
        - AWSLambdaSQSQueueExecutionRole
        - AmazonSNSFullAccess
        - AmazonSQSFullAccess
      Tracing: Active
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes